Repository canonical/tempo-coordinator-k8s-operator, pull requests merged in 2025-05, with the labels that each got.

#150 catch error on charm-tracing-config if leader databag is empty
  lib/charms/tempo_coordinator_k8s/v0/tracing.py
  pyproject.toml
  tests/integration/test_integration.py
  tests/integration/test_self_monitoring.py
  tests/scenario/test_tracing_provider.py
  tests/scenario/test_tracing_requirer.py
  tests/unit/test_charm_tracing_units.py
  tox.ini
  uv.lock
Labels: Libraries: Out of sync

#155 Simplify nginx config generation
  pyproject.toml
  src/charm.py
  src/nginx_config.py
  tests/scenario/test_nginx.py
  uv.lock
Labels: Libraries: OK

#159 chore: finalize track 1
  .github/workflows/release.yaml
  pyproject.toml
  uv.lock
Labels: Libraries: OK

#161 chore: release to track 2
  .github/workflows/release.yaml
  charmcraft.yaml
  lib/charms/loki_k8s/v1/loki_push_api.py
  pyproject.toml
  tests/integration/helpers.py
  tests/integration/test_ingress.py
  tests/integration/test_tls.py
  uv.lock
Labels: Libraries: OK

#158 Use the standalone `coordinated-workers` PyPI package
  pyproject.toml
  src/charm.py
  src/nginx_config.py
  src/tempo.py
  src/tempo_config.py
  tests/integration/helpers.py
  tests/integration/test_integration.py
  tests/interface/conftest.py
  tests/scenario/conftest.py
  tests/scenario/helpers.py
  tests/scenario/test_charm_statuses.py
  tests/scenario/test_nginx.py
  tests/scenario/test_tempo_clustered.py
  tests/unit/test_coherence.py
  uv.lock
Labels: Charm Libraries: Out of Sync

#151 Add `constraints` TF input variable
  terraform/README.md
  terraform/main.tf
  terraform/variables.tf
Labels: Charm Libraries: OK
